export default [
  {
    path: '/user',
    component: '../layouts/UserLayout',
    routes: [
      {
        name: 'login',
        path: '/user/login',
        component: './user/login',
      },
    ],
  },
  {
    path: '/',
    component: '../layouts/SecurityLayout',
    routes: [
      {
        path: '/',
        component: '../layouts/BasicLayout',
        authority: [
          'admin',
          'user',
          'qyllr',
          'qyanfzr',
          'qyagy',
          'qyfr',
          'zjllr',
          'zjyw',
          'bxllr',
          'bxywy',
          'yjjry',
          'dsfry',
        ],
        routes: [
          {
            path: '/',
            redirect: '/info',
          },
          {
            path: '/info',
            icon: 'table',
            name: 'info',
            authority: ['admin', 'user', 'qyllr', 'zjllr', 'zjyw', 'bxllr', 'yjjry', 'dsfry'],
            routes: [
              {
                path: '/info',
                redirect: '/info/companylist',
              },
              {
                path: '/info/companylist',
                name: 'companylist',
                component: './info/CompanyList',
                authority: ['admin', 'yjjry'],
              },
              {
                path: '/info/companyinfo/:id',
                name: 'companyinfo',
                component: './info/CompanyInfo',
                hideInMenu: true,
                authority: ['admin', 'yjjry'],
              },
              {
                path: '/info/companyinfo/:id/legalperson',
                name: 'legalperson',
                component: './info/CompanyInfo/LegalPerson',
                hideInMenu: true,
                // authority: ['qy100'],
              },
              {
                path: '/info/securitymanager',
                name: 'manager',
                component: './info/SecurityManager',
                authority: ['admin', 'qyllr'],
              },
              {
                path: '/info/securitymanagerdetail',
                name: 'organization',
                component: './info/SecurityManagerDetail',
                hideInMenu: true,
                authority: ['admin', 'qyllr'],
              },
              {
                path: '/info/proxylist',
                name: 'proxylist',
                component: './info/ProxyOrganization',
                authority: ['admin', 'zjllr'],
              },
              {
                path: '/info/proxyinfo',
                name: 'proxyinfo',
                component: './info/ProxyInfo',
                hideInMenu: true,
                authority: ['admin', 'zjllr'],
              },
              {
                path: '/info/proxycontractputonrecords',
                name: 'proxycontractputonrecords',
                component: './info/ProxyContractPutOnRecords',
                authority: ['admin', 'zjyw'],
              },
              {
                path: '/info/contractputonrecords',
                name: 'contractputonrecords',
                component: './info/ContractPutOnRecords',
                authority: ['admin', 'zjyw'],
                hideInMenu: true,
              },
              {
                path: '/info/addcontract',
                name: 'addcontract',
                component: './info/AddContract',
                hideInMenu: true,
                authority: ['admin', 'zjyw'],
              },
              {
                path: '/info/insurancelist',
                name: 'insurancelist',
                component: './info/InsuranceOrganization',
                authority: ['admin', 'dsfry'],
              },
              {
                path: '/info/insuranceinfo',
                name: 'insuranceinfo',
                component: './info/InsuranceOrganizationInfo',
                hideInMenu: true,
                authority: ['admin', 'dsfry'],
              },
              {
                path: '/info/insurancesalesmanmanagement',
                name: 'insurancesalesmanmanagement',
                component: './info/InsuranceSalesmanManagement',
                authority: ['admin', 'bxllr'],
              },
              {
                path: '/info/addinsurancesalesman',
                name: 'addinsurancesalesman',
                component: './info/AddInsuranceSalesman',
                hideInMenu: true,
                // authority: ['yjj100'],
              },
            ],
          },
          {
            path: '/risk',
            icon: 'table',
            name: 'risk',
            authority: ['admin', 'user', 'qyagy', 'qyfr', 'zjyw', 'yjjry'],
            routes: [
              {
                path: '/risk',
                redirect: '/risk/diagram',
              },
              {
                path: '/risk/diagramsearchent',
                name: 'diagramsearchent',
                component: './risk/DiagramSearchEnt',
                authority: ['admin', 'zjyws'],
              },
              {
                path: '/risk/diagramupload',
                name: 'diagramupload',
                component: './risk/DiagramUpload',
                hideInMenu: true,
                authority: ['admin', 'zjyw'],
              },
              {
                path: '/risk/diagramdetail/:id',
                name: 'diagramdetail',
                component: './risk/DiagramDetail',
                // hideInMenu: true,
                authority: ['admin', 'zjyw'],
              },
              {
                path: '/risk/diagramlist',
                name: 'diagramlist',
                component: './risk/DiagramList',
                hideInMenu: true,
                // authority: ['yjj100'],
              },
              {
                path: '/risk/risklistmanagement',
                name: 'risklistmanagement',
                component: './risk/RiskListManagement',
                authority: ['admin', 'zjyw', 'qyagy'],
              },
              {
                path: '/risk/securityrisklist',
                name: 'securityrisklist',
                component: './risk/SecurityRiskList',
                hideInMenu: true,
                authority: ['admin', 'zjyw', 'qyagy'],
              },
              {
                path: '/risk/risklistdetail',
                name: 'risklistdetail',
                component: './risk/RiskListDetail',
                hideInMenu: true,
                authority: ['admin', 'zjyw', 'qyagy'],
              },
              {
                path: '/risk/riskchecklist',
                name: 'riskchecklist',
                component: './risk/RiskCheckList',
                hideInMenu: true,
                // authority: ['yjj100'],
              },
              {
                path: '/risk/riskcheckdetail/:id',
                name: 'riskcheckdetail',
                component: './risk/RiskCheckDetail',
                // hideInMenu: true,
                authority: ['admin', 'qyagy'],
              },
              {
                path: '/risk/legalpersoncheck',
                name: 'legalpersoncheck',
                component: './risk/LegalPersonCheck',
                hideInMenu: true,
                // authority: ['qy500'],
              },
              {
                path: '/risk/riskwarning',
                name: 'riskwarning',
                component: './risk/RiskWarning',
                hideInMenu: true,
              },
              {
                path: '/risk/hiddendangerlist',
                name: 'hiddendangerlist',
                component: './risk/HiddenDangerList',
                hideInMenu: true,
              },
              {
                path: '/risk/riskmanagepromise',
                name: 'riskmanagepromise',
                component: './risk/RiskManagePromise',
                hideInMenu: true,
                // authority: ['qy100'],
              },
              {
                path: '/risk/riskreadytochecklist',
                name: 'riskreadytochecklist',
                component: './risk/RiskReadyToCheckList',
                hideInMenu: true,
                // authority: ['yjj100'],
              },
              {
                path: '/risk/riskpromisecheck/:id',
                name: 'riskpromisecheck',
                component: './risk/RiskManagePromiseCheck',
                hideInMenu: true,
                // authority: ['yjj100'],
              },
              {
                path: '/risk/dailyriskmanagepromise',
                name: 'dailyriskmanagepromise',
                component: './risk/DailyRiskManagePromise',
                authority: ['admin', 'qyfr'],
              },
              {
                path: '/risk/dailyriskmanagepromiserecord',
                name: 'dailyriskmanagepromiserecord',
                component: './risk/DailyRiskManagePromise/RiskManagePromiseRecord',
                hideInMenu: true,
                authority: ['admin', 'qyfr'],
              },
              {
                path: '/risk/chemicalsmanage',
                name: 'chemicalsmanage',
                component: './risk/ChemicalsManage',
                authority: ['admin', 'qyagy'],
              },
              {
                path: '/risk/chemicalsmanageinforecord',
                name: 'chemicalsmanageinforecord',
                component: './risk/ChemicalsManage/ChemicalsInfoRecord',
                hideInMenu: true,
                authority: ['admin', 'qyagy'],
              },
              {
                path: '/risk/chemicalsquery',
                name: 'chemicalsquery',
                component: './risk/ChemicalsQuery',
                authority: ['admin', 'qyagy', 'yjjry'],
              },
              {
                path: '/risk/tbdmission',
                name: 'tbdmission',
                component: './risk/TBDMission',
                hideInMenu: true,
                // authority: ['qy200'],
              },
              {
                path: '/risk/checksituationrecord',
                name: 'checksituationrecord',
                component: './risk/CheckSituationRecord',
                hideInMenu: true,
                // authority: ['qy200'],
              },
              {
                path: '/risk/hiddentroubleshoot',
                name: 'hiddentroubleshoot',
                component: './risk/HiddenTroubleShoot',
                // authority: ['qy200'],
              },
              {
                path: '/risk/hiddentroubleshootsituation',
                name: 'hiddentroubleshootsituation',
                component: './risk/HiddenTroubleShootSituation',
                authority: ['admin', 'zjyw', 'qyagy'],
              },
              {
                path: '/risk/hiddentroubleshootsituationrecord',
                name: 'hiddentroubleshootsituationrecord',
                component: './risk/HiddenTroubleShootSituationRecord',
                hideInMenu: true,
                authority: ['admin', 'zjyw', 'qyagy'],
              },
              {
                path: '/risk/tbdhiddentroublelist',
                name: 'tbdhiddentroublelist',
                component: './risk/TBDHiddenTroubleList',
                authority: ['admin', 'qyfr', 'qyagy'],
              },
              {
                path: '/risk/hiddentroubleresolverecord',
                name: 'hiddentroubleresolverecord',
                component: './risk/HiddenTroubleResolveRecord',
                hideInMenu: true,
                authority: ['admin', 'qyfr', 'qyagy'],
              },
              {
                path: '/risk/hiddentrouberesolvechecklist',
                name: 'hiddentrouberesolvechecklist',
                component: './risk/HiddenTroubleResolveCheckList',
                authority: ['admin', 'qyfr', 'qyagy'],
              },
              {
                path: '/risk/hiddentroubleresolvecheck',
                name: 'hiddentroubleresolvecheck',
                component: './risk/HiddenTroubleResolveCheck',
                hideInMenu: true,
                authority: ['admin', 'qyfr', 'qyagy'],
              },
              {
                path: '/risk/hiddentroubleresolvetbdmiddlechecklist',
                name: 'hiddentroubleresolvetbdmiddlechecklist',
                component: './risk/HiddenTroubleResolveTBDMiddleCheckList',
                hideInMenu: true,
                authority: ['admin', 'zjyw'],
              },
              {
                path: '/risk/hiddentroubleresolvetbdmiddlecheck',
                name: 'hiddentroubleresolvetbdmiddlecheck',
                component: './risk/HiddenTroubleResolveTBDMiddleCheck',
                hideInMenu: true,
                authority: ['admin', 'zjyw'],
              },
              {
                path: '/risk/hiddentroubleresolvesituation',
                name: 'hiddentroubleresolvesituation',
                component: './risk/HiddenTroubleResolveSituation',
                authority: ['admin', 'yjjry'],
              },
              {
                path: '/risk/hiddentroubleresolvetmiddlecheckstatus',
                name: 'hiddentroubleresolvetmiddlecheckstatus',
                component: './risk/HiddenTroubleResolveMiddleCheckStatus',
                hideInMenu: true,
                authority: ['admin', 'yjjry'],
              },
            ],
          },
          {
            path: '/rule',
            icon: 'table',
            name: 'rule',
            authority: ['admin', 'qyagy'],
            routes: [
              {
                path: '/rule',
                redirect: '/rule/rulevindicate',
              },
              {
                path: '/rule/rulevindicate',
                name: 'rulevindicate',
                component: './rule/RuleVindicate',
              },
              {
                path: '/rule/rulevindicatedetail',
                name: 'rulevindicatedetail',
                component: './rule/RuleVindicateDetail',
              },
              {
                path: '/rule/ruleexecute',
                name: 'ruleexecute',
                component: './rule/RuleExecute',
              },
              {
                path: '/rule/ruleexecutedetail',
                name: 'ruleexecutedetail',
                component: './rule/RuleExecuteDetail',
              },
              {
                path: '/rule/ruleexecutedetailadd',
                name: 'ruleexecutedetailadd',
                component: './rule/RuleExecuteDetail/RuleExecuteDetailAdd',
                hideInMenu: true,
              },
            ],
          },
          {
            path: '/yjjsupervise',
            icon: 'table',
            name: 'yjjsupervise',
            authority: ['admin', 'yjjry'],
            routes: [
              {
                path: '/yjjsupervise',
                redirect: '/yjjsupervise/reportmanage',
              },
              {
                path: '/yjjsupervise/entsearch',
                name: 'entsearch',
                component: './yjjsupervise/EntSearch',
              },
              {
                path: '/yjjsupervise/workadviserecord',
                name: 'workadviserecord',
                component: './yjjsupervise/WorkAdvise/Record',
                hideInMenu: true,
              },
              {
                path: '/yjjsupervise/workadvisequery',
                name: 'workadvisequery',
                component: './yjjsupervise/WorkAdvise/Query',
              },
              {
                path: '/yjjsupervise/admonitiontalkrecord',
                name: 'admonitiontalkrecord',
                component: './yjjsupervise/AdmonitionTalk/Record',
                hideInMenu: true,
              },
              {
                path: '/yjjsupervise/admonitiontalkquery',
                name: 'admonitiontalkquery',
                component: './yjjsupervise/AdmonitionTalk/Query',
              },
              {
                path: '/yjjsupervise/admonitiontalkdetail',
                name: 'admonitiontalkdetail',
                component: './yjjsupervise/AdmonitionTalk/Detail',
                hideInMenu: true,
              },
              {
                path: '/yjjsupervise/entcreditratingmanagement',
                name: 'entcreditratingmanagement',
                component: './yjjsupervise/EntCreditRatingManagement',
              },
              {
                path: '/yjjsupervise/entcreditratingmanagementrecord',
                name: 'entcreditratingmanagementrecord',
                component: './yjjsupervise/EntCreditRatingManagement/Record',
                hideInMenu: true,
              },
              {
                path: '/yjjsupervise/entcreditmanagement',
                name: 'entcreditmanagement',
                component: './yjjsupervise/EntCreditManagement',
              },
            ],
          },
          {
            path: '/report',
            icon: 'table',
            name: 'report',
            routes: [
              {
                path: '/report',
                redirect: '/report/reportmanage',
              },
              {
                path: '/report/reportmanage',
                name: 'reportmanage',
                component: './report/ReportManage',
              },
            ],
          },
          {
            path: '/system',
            icon: 'table',
            name: 'system',
            routes: [
              {
                path: '/system',
                redirect: '/system/dangecheckrule',
              },
              {
                path: '/system/authoritymanage',
                name: 'authoritymanage',
                component: './system/AuthorityManage',
              },
              {
                path: '/system/emergencymanage',
                name: 'emergencymanage',
                component: './system/EmergencyManage',
              },
              {
                path: '/system/rolemanage',
                name: 'rolemanage',
                component: './system/RoleManage',
              },
              {
                path: '/system/systemlog',
                name: 'systemlog',
                component: './system/SystemLog',
              },
              {
                path: '/system/thirdpartymanage',
                name: 'thirdpartymanage',
                component: './system/ThirdPartyManage',
              },
            ],
          },
          {
            component: './404',
          },
        ],
      },
      {
        component: './404',
      },
    ],
  },
  {
    component: './404',
  },
];
